[2024-04-22T11:43:04.894+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-10T00:00:00+00:00 [queued]>
[2024-04-22T11:43:04.956+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-10T00:00:00+00:00 [queued]>
[2024-04-22T11:43:04.969+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-04-22T11:43:05.008+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): second_task> on 2021-08-10 00:00:00+00:00
[2024-04-22T11:43:05.020+0000] {standard_task_runner.py:60} INFO - Started process 691 to run task
[2024-04-22T11:43:05.032+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-10T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpy7z13e3b']
[2024-04-22T11:43:05.041+0000] {standard_task_runner.py:88} INFO - Job 44: Subtask second_task
[2024-04-22T11:43:05.127+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-22T11:43:05.277+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-10T00:00:00+00:00 [running]> on host 44bc093743d3
[2024-04-22T11:43:05.630+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-08-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-08-10T00:00:00+00:00'
[2024-04-22T11:43:05.634+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-22T11:43:05.636+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2024-04-22T11:43:05.660+0000] {subprocess.py:86} INFO - Output:
[2024-04-22T11:43:05.662+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1!
[2024-04-22T11:43:05.664+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-22T11:43:05.740+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210810T000000, start_date=20240422T114304, end_date=20240422T114305
[2024-04-22T11:43:05.867+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T11:43:05.947+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
