[2024-04-22T11:43:11.536+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-13T00:00:00+00:00 [queued]>
[2024-04-22T11:43:11.600+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-13T00:00:00+00:00 [queued]>
[2024-04-22T11:43:11.602+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-04-22T11:43:11.803+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): second_task> on 2021-08-13 00:00:00+00:00
[2024-04-22T11:43:11.821+0000] {standard_task_runner.py:60} INFO - Started process 742 to run task
[2024-04-22T11:43:11.844+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-13T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp5i0uajt3']
[2024-04-22T11:43:11.860+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask second_task
[2024-04-22T11:43:11.969+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-22T11:43:12.284+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-13T00:00:00+00:00 [running]> on host 44bc093743d3
[2024-04-22T11:43:12.913+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-08-13T00:00:00+00:00'
[2024-04-22T11:43:12.939+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-22T11:43:12.960+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2024-04-22T11:43:13.026+0000] {subprocess.py:86} INFO - Output:
[2024-04-22T11:43:13.043+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1!
[2024-04-22T11:43:13.063+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-22T11:43:13.450+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210813T000000, start_date=20240422T114311, end_date=20240422T114313
[2024-04-22T11:43:14.160+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T11:43:14.285+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
